import { NextRequest, NextResponse } from 'next/server';
import { consumeInMemoryLimit } from '@/lib/abuse-prevention';
import { ApiError, apiErrorResponse } from '@/lib/api-response';
import { requireCurrentUser } from '@/lib/auth';
import { normalizeText, validateContent } from '@/lib/content-quality';
import { feedbackCategories, feedbackKey, safeCurrentPage } from '@/lib/feedback';
import { assertBetaWriteAccess } from '@/lib/release-controls';
import { prisma } from '@/lib/prisma';

export async function GET(request: NextRequest) { try { const user = await requireCurrentUser(); const feedback = await prisma.feedback.findMany({ where: { submitterId: user.id }, orderBy: { createdAt: 'desc' }, take: 50, select: { id: true, category: true, title: true, status: true, resolutionSummary: true, createdAt: true } }); return NextResponse.json({ ok: true, feedback }); } catch (error) { return apiErrorResponse(error, 'Could not load your feedback.', request, 'feedback'); } }
export async function POST(request: NextRequest) { try { const user = await requireCurrentUser(); await assertBetaWriteAccess(user, 'feedback_system'); const limit = consumeInMemoryLimit(`feedback:${user.id}`, { limit: 8, windowMs: 24*60*60_000, message: 'You have shared several feedback items today. Try again later.' }); if (!limit.allowed) throw new ApiError(429, limit.message ?? 'Too many feedback submissions.', 'feedback_rate_limited'); const body = await request.json() as { category?: string; title?: string; description?: string; currentPage?: string; browserContext?: string }; const title = normalizeText(body.title), description = normalizeText(body.description); if (!feedbackCategories.includes(body.category as never)) throw new ApiError(400, 'Choose a feedback category.', 'invalid_feedback_category'); const tq=validateContent(title,{label:'Feedback title',minLength:5,maxLength:120,allowLinks:0}),dq=validateContent(description,{label:'Feedback description',minLength:20,maxLength:3000,allowLinks:2}); if(tq.errors.length||dq.errors.length) throw new ApiError(400,[...tq.errors,...dq.errors][0],'invalid_feedback'); const key=feedbackKey(user.id,title,description); const item=await prisma.feedback.create({data:{submitterId:user.id,category:body.category as never,title,description,currentPage:safeCurrentPage(body.currentPage),browserContext:normalizeText(body.browserContext).slice(0,160)||undefined,idempotencyKey:key}}); await prisma.feedbackStatusHistory.create({data:{feedbackId:item.id,status:'NEW',actorId:user.id}}); return NextResponse.json({ok:true,feedbackId:item.id}); } catch(error){const duplicate=typeof error==='object'&&error!==null&&'code'in error&&error.code==='P2002';return apiErrorResponse(duplicate?new ApiError(409,'This feedback was already submitted.','duplicate_feedback'):error,'Could not submit feedback.',request,'feedback');} }
