import type {
  Answer,
  ClaimReality,
  College,
  ExperiencePost,
  Question,
  User,
  Validation,
  WhatWorksPost,
} from './types';

export const colleges: College[] = [
  {
    id: 'c1',
    name: 'Aster Valley Institute of Technology',
    slug: 'aster-valley-institute-of-technology',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    officialWebsite: 'https://example.edu/aster-valley',
    affiliation: 'Western Deccan Technical University',
    courses: ['Computer Science', 'Electronics', 'Mechanical', 'Data Science'],
    feeRange: 'INR 1.4L - 1.9L per year',
    admissionModes: ['State CET', 'Management quota', 'Lateral entry'],
  },
  {
    id: 'c2',
    name: 'Northstar College of Engineering',
    slug: 'northstar-college-of-engineering',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    officialWebsite: 'https://example.edu/northstar',
    affiliation: 'Rajasthan Applied Sciences University',
    courses: ['Computer Science', 'Civil', 'Electrical', 'AI and ML'],
    feeRange: 'INR 95K - 1.5L per year',
    admissionModes: ['JEE Main', 'State counseling'],
  },
  {
    id: 'c3',
    name: 'Riverbend Arts and Science University',
    slug: 'riverbend-arts-and-science-university',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    officialWebsite: 'https://example.edu/riverbend',
    affiliation: 'Autonomous',
    courses: ['BCA', 'BBA', 'Psychology', 'Visual Communication'],
    feeRange: 'INR 70K - 1.2L per year',
    admissionModes: ['Merit list', 'Interview'],
  },
];

export const users: User[] = [
  { id: 'u1', name: 'Riya Menon', email: 'riya@example.com', anonymousDisplayName: 'Curious Aspirant', role: 'ASPIRANT', verificationLevel: 1, interestedBranch: 'CSE' },
  { id: 'u2', name: 'Kabir Shah', email: 'kabir@example.com', anonymousDisplayName: 'CSE Hosteller', role: 'CURRENT_STUDENT', verificationLevel: 3, collegeId: 'c1', branch: 'CSE', batch: '2027', year: '2nd year', hostelStatus: 'Hostel' },
  { id: 'u3', name: 'Nisha Rao', email: 'nisha@example.com', anonymousDisplayName: 'CSE Alum', role: 'ALUMNI', verificationLevel: 3, collegeId: 'c1', branch: 'CSE', batch: '2024' },
  { id: 'u4', name: 'Arjun Dev', email: 'arjun@example.com', anonymousDisplayName: 'Northstar Hosteller', role: 'CURRENT_STUDENT', verificationLevel: 2, collegeId: 'c2', branch: 'AI and ML', batch: '2027', year: '2nd year' },
  { id: 'u5', name: 'Maya Philip', email: 'maya@example.com', anonymousDisplayName: 'Riverbend Grad', role: 'ALUMNI', verificationLevel: 3, collegeId: 'c3', branch: 'BCA', batch: '2023' },
  { id: 'u6', name: 'Yorai Moderator', email: 'moderator@example.com', anonymousDisplayName: 'Yorai Moderator', role: 'MODERATOR', verificationLevel: 1 },
  { id: 'u7', name: 'Ira Sen', email: 'ira@example.com', anonymousDisplayName: 'ECE Day Scholar', role: 'CURRENT_STUDENT', verificationLevel: 2, collegeId: 'c1', branch: 'ECE', batch: '2026', year: '3rd year', hostelStatus: 'Day scholar' },
];

export const questions: Question[] = [
  {
    id: 'q10',
    collegeId: 'c1',
    userId: 'u1',
    title: 'How accessible are CSE labs for first-year students?',
    body: 'I’m considering CSE here and want to understand whether labs are actually accessible for practice outside scheduled class hours. I’m especially interested in whether first-year students can use systems for coding practice, mini projects, or hackathon preparation. Hostel student perspective would help too.',
    category: 'Labs and resources',
    branch: 'CSE',
    status: 'ANSWERED',
    lastActivity: 'Updated this week',
    lastActiveDate: '2026-07-08',
    freshnessLabel: 'Fresh student context',
    participantContext: 'Aspirant asking, CSE current students responding, alumni marked as past context',
    topicTags: ['labs', 'first year', 'CSE', 'projects', 'hostel'],
    latestReplies: [
      'Current student: Extra practice usually needs faculty or lab assistant permission.',
      'Current student: Personal setup is still more reliable for daily coding practice.',
    ],
    contextBadge: 'Context attached',
    attachment: {
      label: 'Lab schedule screenshot',
      status: 'Context attached · Privacy checked',
      description: 'Shared by a current student. Personal details hidden.',
    },
    summary: 'Students say CSE labs are useful during scheduled sessions, but personal laptop setup is still important for regular coding practice. Extra lab access may be possible with permission or during events/hackathons.',
    freshnessSummary: 'Updated this week · Current students responded · Alumni context marked as past experience',
    currentStudentSignal: 'Current students responding',
    reconfirmationSignal: 'Branch-specific discussion',
    reportTone: 'Report concern',
  },
  {
    id: 'q1',
    collegeId: 'c1',
    userId: 'u1',
    title: 'How easy is it to access labs after class?',
    body: 'I want to practice outside scheduled lab hours.',
    category: 'Labs and resources',
    branch: 'Computer Science',
    status: 'ANSWERED',
    lastActivity: '2 days ago',
    lastActiveDate: '2026-07-06',
    freshnessLabel: 'Fresh student context',
    participantContext: 'Aspirant asking, current students responding, alumni adding context',
    topicTags: ['labs', 'first year', 'Computer Science'],
    latestReplies: ['Current student: Project teams can request slots near submissions.', 'Alumni: Ask seniors which lab assistant handles open sessions.'],
    contextBadge: 'Context attached',
    currentStudentSignal: 'Current students responding',
    reconfirmationSignal: 'Reconfirmed by current students',
    reportTone: 'Report concern',
  },
  {
    id: 'q2',
    collegeId: 'c1',
    userId: 'u1',
    title: 'How do first-year students handle attendance expectations?',
    body: 'Trying to understand day-to-day rhythm without turning it into a rule scare.',
    category: 'Attendance',
    status: 'ANSWERED',
    lastActivity: '5 days ago',
    lastActiveDate: '2026-07-03',
    freshnessLabel: 'Fresh student context',
    participantContext: 'Aspirants and alumni comparing batch context',
    topicTags: ['attendance', 'first year', 'daily rhythm'],
    latestReplies: ['Current student: Communicate early if you need an exception.', 'Alumni: Documentation helped when submitted on time.'],
    currentStudentSignal: 'Current students responded recently',
    reconfirmationSignal: 'Needs more branch context',
    reportTone: 'Report concern',
  },
  {
    id: 'q3',
    collegeId: 'c2',
    userId: 'u1',
    title: 'What is hostel Wi-Fi like during exams?',
    body: 'Is it stable enough for online study?',
    category: 'Hostel',
    status: 'OPEN',
    lastActivity: '1 day ago',
    lastActiveDate: '2026-07-07',
    freshnessLabel: 'Updated this week',
    participantContext: 'Aspirant asking, hostellers sharing current context',
    topicTags: ['hostel', 'exams', 'study routine'],
    latestReplies: ['Current student: Notes and recorded lectures work better before evening peak time.'],
    contextBadge: 'Student-added context',
    currentStudentSignal: 'Current students responding',
    reconfirmationSignal: 'Changed recently',
    reportTone: 'Report concern',
  },
  {
    id: 'q4',
    collegeId: 'c2',
    userId: 'u1',
    title: 'Which student clubs actually help first-years find peers?',
    body: 'Looking for practical peer learning and small build groups.',
    category: 'Clubs',
    branch: 'AI and ML',
    status: 'ANSWERED',
    lastActivity: '4 days ago',
    lastActiveDate: '2026-07-04',
    freshnessLabel: 'Fresh student context',
    participantContext: 'Current students and aspirants discussing clubs',
    topicTags: ['clubs', 'first year', 'AI and ML', 'projects'],
    latestReplies: ['Current student: The coding circle is useful for onboarding.', 'Current student: Club value depends on current student leads.'],
    currentStudentSignal: 'Current students responding',
    reconfirmationSignal: 'Branch-specific discussion',
    reportTone: 'Report concern',
  },
  {
    id: 'q5',
    collegeId: 'c3',
    userId: 'u1',
    title: 'Do BCA students get project mentoring?',
    body: 'I care about portfolio support and feedback habits.',
    category: 'Faculty',
    branch: 'BCA',
    status: 'ANSWERED',
    lastActivity: '3 days ago',
    lastActiveDate: '2026-07-05',
    freshnessLabel: 'Reconfirmed by current students',
    participantContext: 'Aspirant asking, alumni sharing path context',
    topicTags: ['projects', 'BCA', 'mentoring'],
    latestReplies: ['Alumni: Form teams early so faculty can see steady progress.', 'Alumni: A working demo opens better mentoring conversations.'],
    contextBadge: 'Shared context',
    currentStudentSignal: 'Current students should update this',
    reconfirmationSignal: 'Needs current student update',
    reportTone: 'Report concern',
  },
  {
    id: 'q6',
    collegeId: 'c1',
    userId: 'u1',
    title: 'Is the old electronics lab access advice still true?',
    body: 'I found older student notes about limited component access. Has this changed for current batches?',
    category: 'Labs and resources',
    branch: 'Electronics',
    status: 'OPEN',
    lastActivity: '18 months ago',
    lastActiveDate: '2025-01-12',
    freshnessLabel: 'Needs current context',
    participantContext: 'Aspirant asking, alumni context available, current students invited',
    topicTags: ['labs', 'Electronics', 'current update needed'],
    latestReplies: ['Alumni: In 2024 we coordinated as a batch before practical weeks.'],
    contextBadge: 'Shared context',
    currentStudentSignal: 'Current students should update this',
    reconfirmationSignal: 'May need current context',
    reportTone: 'Report concern',
  },
  {
    id: 'q7',
    collegeId: 'c2',
    userId: 'u1',
    title: 'Are small project teams forming across branches this year?',
    body: 'I want to understand whether first-year students can find collaborators outside their own branch.',
    category: 'Clubs',
    status: 'ANSWERED',
    lastActivity: '8 months ago',
    lastActiveDate: '2025-11-02',
    freshnessLabel: 'Recent student context',
    participantContext: 'Aspirants and current students comparing club spaces',
    topicTags: ['projects', 'clubs', 'first year', 'collaboration'],
    latestReplies: ['Current student: Build sessions happen through the coding circle more than formal announcements.'],
    contextBadge: 'Context attached',
    currentStudentSignal: 'Current students responded recently',
    reconfirmationSignal: 'Branch-specific discussion',
    reportTone: 'Report concern',
  },
  {
    id: 'q8',
    collegeId: 'c3',
    userId: 'u1',
    title: 'How useful was BCA project mentoring for older batches?',
    body: 'I saw alumni mention progress checkpoints. Has a current student reconfirmed this recently?',
    category: 'Projects',
    branch: 'BCA',
    status: 'ANSWERED',
    lastActivity: '1 month ago',
    lastActiveDate: '2026-06-08',
    freshnessLabel: 'Reconfirmed by current students',
    participantContext: 'Alumni path shared, current students recently reconfirmed',
    topicTags: ['BCA', 'projects', 'portfolio', 'mentoring'],
    latestReplies: ['Current student: Checkpoints still happen, but the best feedback comes when you show a working demo.'],
    contextBadge: 'Student-added context',
    currentStudentSignal: 'Current students responding',
    reconfirmationSignal: 'Reconfirmed by current students',
    reportTone: 'Report concern',
  },
  {
    id: 'q9',
    collegeId: 'c3',
    userId: 'u5',
    title: 'Past experience: how admin follow-ups worked in 2022',
    body: 'Sharing this as archive context only. Current students should update if the process has changed.',
    category: 'Campus life',
    branch: 'BCA',
    status: 'OPEN',
    lastActivity: '3 years ago',
    lastActiveDate: '2023-04-20',
    freshnessLabel: 'Past experience',
    participantContext: 'Alumni archive context, current students invited to update',
    topicTags: ['BCA', 'campus life', 'archive context'],
    latestReplies: ['Alumni: Written summaries before office visits helped keep requests clear.'],
    currentStudentSignal: 'Current students should update this',
    reconfirmationSignal: 'Past experience. Needs current context.',
    reportTone: 'Report concern',
  },
];

export const answers: Answer[] = [
  {
    id: 'a14',
    questionId: 'q10',
    collegeId: 'c1',
    userId: 'u2',
    body: 'In first year, lab access is mostly tied to scheduled sessions. For extra practice, you usually need faculty or lab assistant permission. It is possible, but not something you can casually walk into every day. Most students use their own laptops for regular coding practice.',
    branchContext: 'CSE, 2nd year, hostel student',
    batchContext: 'Batch 2027',
    studentTypeContext: 'Current student',
    createdAt: '2026-07-08',
    contextBadge: 'Context attached',
    communityContext: 'Branch-specific',
    communityCounts: [
      { label: 'Matches my experience', count: 8 },
      { label: 'Partly true', count: 2 },
      { label: 'Changed recently', count: 1 },
    ],
  },
  {
    id: 'a15',
    questionId: 'q10',
    collegeId: 'c1',
    userId: 'u2',
    body: 'This improved a little this semester. Before internal hackathons, labs were opened for extra slots. But for normal daily practice, personal setup is still more reliable. Seniors usually help more than the official process.',
    branchContext: 'CSE, 3rd year, day scholar',
    batchContext: 'Batch 2026',
    studentTypeContext: 'Current student',
    createdAt: '2026-07-07',
    communityContext: 'Changed recently',
    communityCounts: [
      { label: 'Matches my experience', count: 11 },
      { label: 'Changed recently', count: 3 },
    ],
  },
  {
    id: 'a16',
    questionId: 'q10',
    collegeId: 'c1',
    userId: 'u3',
    body: 'When I was there, lab access outside class was limited. But this may be outdated now. Current students should confirm the latest situation.',
    branchContext: 'CSE alumni',
    batchContext: '2024 batch',
    studentTypeContext: 'Alumni',
    createdAt: '2024-05-12',
    communityContext: 'Past experience. Needs current context.',
    communityCounts: [
      { label: 'Past experience', count: 1 },
      { label: 'Needs current context', count: 1 },
    ],
  },
  {
    id: 'a17',
    questionId: 'q10',
    collegeId: 'c1',
    userId: 'u2',
    body: 'As a first-year hostel student, I’d say bring your own laptop if possible. Labs help for classes, but for self-learning and projects, you shouldn’t fully depend on them.',
    branchContext: 'CSE, 1st year, hostel student',
    batchContext: 'Batch 2027',
    studentTypeContext: 'Current student',
    createdAt: '2026-07-08',
    communityContext: 'Matches my experience',
    communityCounts: [
      { label: 'Matches my experience', count: 6 },
    ],
  },
  { id: 'a1', questionId: 'q1', collegeId: 'c1', userId: 'u2', body: 'Scheduled labs are reliable. Extra access usually needs faculty permission, but project teams can get slots near submissions.', branchContext: 'Computer Science', batchContext: '2026', studentTypeContext: 'Current student', createdAt: '2026-07-06', contextBadge: 'Context attached', communityContext: 'Matches my experience' },
  { id: 'a2', questionId: 'q1', collegeId: 'c1', userId: 'u3', body: 'This was similar in my batch. Ask seniors which lab assistant is handling open sessions before planning evening work.', branchContext: 'Electronics', batchContext: '2024', studentTypeContext: 'Alumni', createdAt: '2026-07-05', communityContext: 'Branch-specific' },
  { id: 'a3', questionId: 'q2', collegeId: 'c1', userId: 'u2', body: 'First-year attendance is watched closely. Faculty are usually reasonable if you communicate early.', batchContext: '2026', studentTypeContext: 'Current student', createdAt: '2026-07-03', communityContext: 'Partly true' },
  { id: 'a4', questionId: 'q3', collegeId: 'c2', userId: 'u4', body: 'Wi-Fi is fine for notes and recorded lectures, but video calls can dip after dinner.', branchContext: 'AI and ML', batchContext: '2027', studentTypeContext: 'Current student', createdAt: '2026-07-07', contextBadge: 'Student-added context', communityContext: 'Changed recently' },
  { id: 'a5', questionId: 'q4', collegeId: 'c2', userId: 'u4', body: 'Technical clubs are active when student leads are strong. The coding group is useful for first-year onboarding.', branchContext: 'AI and ML', batchContext: '2027', studentTypeContext: 'Current student', createdAt: '2026-07-04', communityContext: 'Matches my experience' },
  { id: 'a6', questionId: 'q5', collegeId: 'c3', userId: 'u5', body: 'BCA project mentoring depends on the guide, but the department does hold progress checkpoints that keep projects moving.', branchContext: 'BCA', batchContext: '2023', studentTypeContext: 'Alumni', createdAt: '2026-07-05', communityContext: 'Needs more context' },
  { id: 'a7', questionId: 'q5', collegeId: 'c3', userId: 'u5', body: 'Students who form teams early usually get better feedback because faculty can see steady progress.', branchContext: 'BCA', batchContext: '2023', studentTypeContext: 'Alumni', createdAt: '2026-07-04', communityContext: 'I can add context' },
  { id: 'a8', questionId: 'q2', collegeId: 'c1', userId: 'u3', body: 'Medical and event exceptions were accepted when documentation was submitted on time.', branchContext: 'Electronics', batchContext: '2024', studentTypeContext: 'Alumni', createdAt: '2026-07-02', communityContext: 'Past batch context' },
  { id: 'a9', questionId: 'q6', collegeId: 'c1', userId: 'u3', body: 'In 2024, component access needed planning. I would treat this as past context until a current ECE student updates it.', branchContext: 'Electronics', batchContext: '2024', studentTypeContext: 'Alumni', createdAt: '2025-01-12', communityContext: 'Current students should update this' },
  { id: 'a10', questionId: 'q7', collegeId: 'c2', userId: 'u4', body: 'Small teams form through club rooms and weekend build sessions. It is easier if you attend consistently for two or three weeks.', branchContext: 'AI and ML', batchContext: '2027', studentTypeContext: 'Current student', createdAt: '2025-11-02', contextBadge: 'Context attached', communityContext: 'Matches my experience' },
  { id: 'a11', questionId: 'q8', collegeId: 'c3', userId: 'u5', body: 'As alumni, I remember checkpoints helping most when students arrived with a small demo instead of only slides.', branchContext: 'BCA', batchContext: '2023', studentTypeContext: 'Alumni', createdAt: '2024-05-15', communityContext: 'Past experience' },
  { id: 'a12', questionId: 'q8', collegeId: 'c3', userId: 'u4', body: 'Current students I know say checkpoints still happen. The strongest feedback comes after showing a working demo.', branchContext: 'BCA', batchContext: '2027', studentTypeContext: 'Current student', createdAt: '2026-06-08', contextBadge: 'Student-added context', communityContext: 'Reconfirmed by current students' },
  { id: 'a13', questionId: 'q9', collegeId: 'c3', userId: 'u5', body: 'This is archive context from 2022. Please ask a current student before depending on it.', branchContext: 'BCA', batchContext: '2023', studentTypeContext: 'Alumni', createdAt: '2023-04-20', communityContext: 'Past experience. Needs current context.' },
];

export const experiences: ExperiencePost[] = [
  {
    id: 'e7',
    collegeId: 'c1',
    userId: 'u2',
    title: 'Finding a steady CSE routine in first year',
    body: 'My first year became calmer when I stopped waiting for perfect lab access and built a daily laptop-based practice routine with two hostel friends.',
    category: 'Student path',
    branch: 'CSE',
    batch: '2027',
    yearOrBatch: '1st year, batch 2027',
    hostelStatus: 'Hostel student',
    tags: ['CSE', 'first year', 'hostel', 'projects'],
    whatWorked: 'Small peer group, seniors who shared starter projects, and weekend practice blocks.',
    whatDidNotWork: 'Depending only on open lab access for regular coding practice.',
    advice: 'Bring a personal laptop if possible and use labs mainly for scheduled work or event slots.',
    wishIKnewEarlier: 'Seniors are easier to approach when you ask specific project questions.',
    actuallyWorksHere: 'Peer learning circles and planned practice time work better than waiting for formal support.',
    whoThisMayHelp: 'First-year CSE students living in hostel who want to build coding habits early.',
    communityContext: 'Current students say this matches hostel CSE experience this year.',
    recentChanges: 'Internal hackathon slots made lab access better during event weeks.',
    studentContext: 'Current student, CSE, 1st year, hostel, batch 2027',
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Context attached',
    proofStatus: 'Context added',
  },
  {
    id: 'e8',
    collegeId: 'c1',
    userId: 'u3',
    title: 'Past context: how I used seniors for lab preparation',
    body: 'In my batch, lab access outside class was limited, so seniors helped us plan what to practice before scheduled sessions.',
    category: 'Student path',
    branch: 'CSE',
    batch: '2024',
    yearOrBatch: '2024 batch',
    hostelStatus: 'Day scholar',
    tags: ['labs', 'seniors', 'past context'],
    whatWorked: 'Asking seniors for lab manuals, sample problems, and common setup mistakes.',
    whatDidNotWork: 'Assuming old lab access habits would stay the same every semester.',
    advice: 'Treat this as past context and ask current students what has changed.',
    wishIKnewEarlier: 'The best help came from students one or two batches ahead.',
    actuallyWorksHere: 'Preparing before lab hours made scheduled sessions more useful.',
    whoThisMayHelp: 'Students comparing older alumni context with current student updates.',
    communityContext: 'Past experience; current students should update this before relying on it.',
    recentChanges: 'Current students report some extra event-week access now.',
    studentContext: 'Alumni, CSE, 2024 batch',
    freshnessLabel: 'Past experience',
    contextBadge: 'Shared context',
    proofStatus: 'Context added',
  },
  {
    id: 'e9',
    collegeId: 'c1',
    userId: 'u3',
    title: 'Reconfirmed: project groups matter more than formal notices',
    body: 'Older students said project groups mattered, and current students recently reconfirmed that small peer groups still help most.',
    category: 'Student path',
    branch: 'CSE',
    batch: '2024 to 2027',
    yearOrBatch: 'Alumni context, reconfirmed by current students',
    hostelStatus: 'Mixed',
    tags: ['projects', 'peer group', 'reconfirmed'],
    whatWorked: 'Two or three committed peers, one senior mentor, and simple weekly demos.',
    whatDidNotWork: 'Waiting for official announcements before starting projects.',
    advice: 'Start small and show working demos to seniors or faculty.',
    wishIKnewEarlier: 'A tiny working prototype attracts better feedback than a big idea.',
    actuallyWorksHere: 'Peer-led project circles are still useful across batches.',
    whoThisMayHelp: 'Students who want to build projects without waiting for a formal program.',
    communityContext: 'Reconfirmed by current CSE students this month.',
    recentChanges: 'Students now use internal hackathon groups to find collaborators.',
    studentContext: 'Alumni, reconfirmed by current CSE students',
    freshnessLabel: 'Reconfirmed by current students',
    contextBadge: 'Student-added context',
    proofStatus: 'Community confirmed',
  },
  {
    id: 'e1',
    collegeId: 'c1',
    userId: 'u2',
    title: 'How I found my CSE learning circle',
    body: 'My first semester felt easier once I joined a small project group and started asking seniors specific questions.',
    category: 'Student path',
    branch: 'Computer Science',
    batch: '2026',
    whatWorked: 'Project groups, coding seniors, scheduled labs',
    whatDidNotWork: 'Extra lab access needs planning',
    advice: 'Find active seniors in the first month.',
    wishIKnewEarlier: 'Most useful help came from peers who had just completed the same subjects.',
    actuallyWorksHere: 'Small project circles and planned lab requests work better than waiting for formal sessions.',
    whoThisMayHelp: 'Aspirants who want a hands-on CSE routine and are comfortable asking peers for help.',
    communityContext: 'Matches my experience from CSE students; branch-specific for lab access.',
    recentChanges: 'More elective workshops this year.',
    studentContext: 'Current student, CSE, batch 2026',
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Context attached',
    proofStatus: 'Context added',
  },
  {
    id: 'e2',
    collegeId: 'c1',
    userId: 'u3',
    title: 'What helped me use Electronics lab time well',
    body: 'I got more from lab sessions when I prepared readings before class and coordinated component needs with classmates.',
    category: 'Student path',
    branch: 'Electronics',
    batch: '2024',
    whatWorked: 'Faculty demos and lab manuals',
    whatDidNotWork: 'Components were sometimes limited',
    advice: 'Coordinate as a batch before practical weeks.',
    wishIKnewEarlier: 'Going in with pre-read notes made faculty guidance much easier to use.',
    actuallyWorksHere: 'Batch coordination and clear lab questions make practical sessions smoother.',
    whoThisMayHelp: 'Students who learn by doing and want to make lab hours count.',
    communityContext: 'Partly true across branches; strongest context from ECE alumni.',
    studentContext: 'Alumni, Electronics, batch 2024',
    freshnessLabel: 'Past experience. Needs current context.',
    contextBadge: 'Shared context',
    proofStatus: 'Community confirmed',
  },
  {
    id: 'e3',
    collegeId: 'c2',
    userId: 'u4',
    title: 'My hostel study rhythm during exam weeks',
    body: 'The campus stays calm during exams, and study groups form naturally if you keep a steady routine.',
    category: 'Student path',
    branch: 'AI and ML',
    batch: '2027',
    whatWorked: 'Study rooms and peer groups',
    whatDidNotWork: 'Evening network congestion',
    advice: 'Download materials before peak hours.',
    wishIKnewEarlier: 'Shared study rooms were more reliable than trying to study only in the room.',
    actuallyWorksHere: 'Offline notes, early downloads, and peer revision groups.',
    whoThisMayHelp: 'Hostel students who need structure and quiet peer accountability.',
    communityContext: 'Changed recently for Wi-Fi; hostel students say timing matters.',
    studentContext: 'Current student, AI and ML, batch 2027',
    freshnessLabel: 'Updated this week',
    contextBadge: 'Student-added context',
    proofStatus: 'Context added',
  },
  {
    id: 'e4',
    collegeId: 'c2',
    userId: 'u4',
    title: 'Finding useful club spaces as a second-year student',
    body: 'Club activity changes with student leads, so attending early meetings helped me find the right peer group.',
    category: 'Student path',
    branch: 'AI and ML',
    batch: '2027',
    whatWorked: 'Coding circle and design club',
    whatDidNotWork: 'Calendar is not always predictable',
    advice: 'Attend the first few meetings before deciding where to spend time.',
    wishIKnewEarlier: 'The value is often in the people you meet, not only the official club calendar.',
    actuallyWorksHere: 'Joining small build sessions and volunteering for tiny tasks.',
    whoThisMayHelp: 'Students looking for project collaborators or first-year peer learning.',
    communityContext: 'Branch-specific and dependent on current student leads.',
    studentContext: 'Current student, AI and ML, batch 2027',
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Context can be added',
    proofStatus: 'Open experience',
  },
  {
    id: 'e5',
    collegeId: 'c3',
    userId: 'u5',
    title: 'Turning my BCA coursework into a portfolio',
    body: 'Course projects became more useful when I shaped them into small demos and asked for feedback early.',
    category: 'Student path',
    branch: 'BCA',
    batch: '2023',
    whatWorked: 'Progress checkpoints and library access',
    whatDidNotWork: 'Industry exposure varied by semester',
    advice: 'Pick a project with a visible demo.',
    wishIKnewEarlier: 'A simple working demo opened more mentoring conversations than a long proposal.',
    actuallyWorksHere: 'Early team formation, demo-first projects, and repeated faculty feedback.',
    whoThisMayHelp: 'Students who want to build a portfolio during regular coursework.',
    communityContext: 'Matches my experience from recent BCA alumni.',
    studentContext: 'Alumni, BCA, batch 2023',
    freshnessLabel: 'Reconfirmed by current students',
    contextBadge: 'Shared context',
    proofStatus: 'Community confirmed',
  },
  {
    id: 'e6',
    collegeId: 'c3',
    userId: 'u5',
    title: 'How I learned to ask for support clearly',
    body: 'There is support on campus, but I got better help when I asked precise questions and followed up politely.',
    category: 'Student path',
    branch: 'BCA',
    batch: '2023',
    whatWorked: 'Approachable faculty and calm study spaces',
    whatDidNotWork: 'Some admin processes needed follow-up',
    advice: 'Keep documents organized and ask for the next step clearly.',
    wishIKnewEarlier: 'A short written summary before meeting faculty saved time for everyone.',
    actuallyWorksHere: 'Clear questions, organized documents, and steady follow-ups.',
    whoThisMayHelp: 'First-generation college students or anyone nervous about asking for help.',
    communityContext: 'Partly true; alumni say department habits can vary.',
    studentContext: 'Alumni, BCA, batch 2023',
    freshnessLabel: 'Needs current context',
    contextBadge: 'Context attached',
    proofStatus: 'Context added',
  },
];

export const claimRealities: ClaimReality[] = [
  { id: 'cr1', collegeId: 'c1', claim: 'Advanced labs are available for all students.', studentReality: 'Scheduled access is consistent; extra practice access is branch and faculty dependent.', category: 'Labs', status: 'BRANCH_SPECIFIC' },
  { id: 'cr2', collegeId: 'c1', claim: 'Career preparation sessions start in second year.', studentReality: 'Students report useful sessions, but self-practice still matters heavily.', category: 'Career prep', status: 'MIXED' },
  { id: 'cr3', collegeId: 'c2', claim: 'Hostel internet supports online study.', studentReality: 'Mostly usable for study resources, with congestion reported during evenings.', category: 'Hostel', status: 'CONFIRMED' },
  { id: 'cr4', collegeId: 'c3', claim: 'Project mentoring is available across departments.', studentReality: 'Students confirm checkpoints, with mentor quality varying by department.', category: 'Projects', status: 'NEEDS_MORE_RESPONSES' },
];

export const whatWorksPosts: WhatWorksPost[] = [
  {
    id: 'w6',
    collegeId: 'c1',
    userId: 'u2',
    title: 'Use the coding circle to find first project partners',
    body: 'The coding circle is the fastest way to meet students who want to build small things consistently.',
    category: 'Clubs',
    branch: 'CSE, first year',
    practicalAdvice: 'Attend two or three sessions before deciding if it is useful for you.',
    whyItHelps: 'You meet seniors and peers who can help unblock setup, project ideas, and practice habits.',
    whoShouldKnow: 'First-year students looking for collaborators.',
    studentContext: 'Current student, CSE, batch 2027',
    tags: ['clubs', 'projects', 'first year'],
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Context attached',
  },
  {
    id: 'w7',
    collegeId: 'c1',
    userId: 'u2',
    title: 'Plan lab requests around project weeks',
    body: 'Labs are most useful when teams request access with a clear purpose instead of expecting daily open access.',
    category: 'Labs and projects',
    branch: 'CSE',
    practicalAdvice: 'Ask with a project plan, team list, and the specific slot you need.',
    whyItHelps: 'Faculty and lab assistants respond better when the request is concrete.',
    whoShouldKnow: 'Students preparing mini projects or internal hackathons.',
    studentContext: 'Current student, CSE, hostel',
    tags: ['labs', 'projects', 'hackathon prep'],
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Student-added context',
  },
  {
    id: 'w8',
    collegeId: 'c1',
    userId: 'u2',
    title: 'Build a first-year rhythm before chasing everything',
    body: 'A simple weekly routine helps more than joining every activity at once.',
    category: 'First-year adjustment',
    branch: 'First year',
    practicalAdvice: 'Keep fixed blocks for classes, practice, rest, and one student group.',
    whyItHelps: 'It keeps college life manageable while you learn how the campus actually works.',
    whoShouldKnow: 'Aspirants and first-year hostel students.',
    studentContext: 'Current student, CSE, batch 2027',
    tags: ['first year', 'hostel', 'routine'],
    freshnessLabel: 'Fresh student context',
    contextBadge: 'Context can be added',
  },
  {
    id: 'w9',
    collegeId: 'c1',
    userId: 'u3',
    title: 'Use hackathons to meet students beyond your section',
    body: 'Hackathons and cross-college events helped students find collaborators faster than normal class groups.',
    category: 'Hackathons and cross-college events',
    branch: 'CSE and Data Science',
    practicalAdvice: 'Join with a small idea, even if it is unfinished, and stay in touch with people you build with.',
    whyItHelps: 'You learn who is serious about projects and discover opportunities outside one classroom.',
    whoShouldKnow: 'Students looking for collaborators, clubs, or early portfolio work.',
    studentContext: 'Alumni context, reconfirmed by current students',
    tags: ['hackathons', 'cross-college', 'projects'],
    freshnessLabel: 'Reconfirmed by current students',
    contextBadge: 'Shared context',
  },
  { id: 'w1', collegeId: 'c1', userId: 'u2', title: 'Ask for lab slots before project week', body: 'Faculty respond better when teams request access with a clear plan.', category: 'Labs', branch: 'Computer Science', freshnessLabel: 'Fresh student context', contextBadge: 'Context attached' },
  { id: 'w2', collegeId: 'c1', userId: 'u3', title: 'Use seniors for elective selection', body: 'Recent seniors know which electives have practical assignments.', category: 'Academics', branch: 'Electronics', freshnessLabel: 'Needs current context', contextBadge: 'Shared context' },
  { id: 'w3', collegeId: 'c2', userId: 'u4', title: 'Join the coding circle early', body: 'It is the quickest way to find peers for practice and mini projects.', category: 'Clubs', branch: 'AI and ML', freshnessLabel: 'Fresh student context', contextBadge: 'Student-added context' },
  { id: 'w4', collegeId: 'c2', userId: 'u4', title: 'Plan downloads before evening hostel hours', body: 'Recorded lectures load better outside peak hostel usage.', category: 'Hostel', freshnessLabel: 'Updated this week', contextBadge: 'Context attached' },
  { id: 'w5', collegeId: 'c3', userId: 'u5', title: 'Turn coursework into portfolio demos', body: 'Faculty feedback is easier to get when your work has a working demo.', category: 'Projects', branch: 'BCA', freshnessLabel: 'Reconfirmed by current students', contextBadge: 'Shared context' },
];

export const validations: Validation[] = [
  { id: 'v1', targetType: 'ANSWER', targetId: 'a1', userId: 'u3', validationType: 'PARTIALLY_TRUE' },
  { id: 'v2', targetType: 'EXPERIENCE_POST', targetId: 'e1', userId: 'u3', validationType: 'MATCHES_MY_EXPERIENCE' },
  { id: 'v3', targetType: 'CLAIM_REALITY', targetId: 'cr1', userId: 'u2', validationType: 'NEEDS_CONTEXT' },
  { id: 'v4', targetType: 'WHAT_WORKS_POST', targetId: 'w3', userId: 'u4', validationType: 'MATCHES_MY_EXPERIENCE' },
];
