import { NextRequest, NextResponse } from 'next/server';
import { ApiError, apiErrorResponse } from '@/lib/api-response';
import { requireCollegeAdminUser } from '@/lib/auth';
import { canTransitionFeedback, feedbackCategories, feedbackStatuses } from '@/lib/feedback';
import { normalizeText } from '@/lib/content-quality';
import { prisma } from '@/lib/prisma';

export async function GET(request: NextRequest) { try { await requireCollegeAdminUser(); const p=new URL(request.url).searchParams,status=p.get('status'),category=p.get('category'); const items=await prisma.feedback.findMany({where:{status:feedbackStatuses.includes(status as never)?status as never:undefined,category:feedbackCategories.includes(category as never)?category as never:undefined},orderBy:{createdAt:'desc'},take:50,select:{id:true,category:true,title:true,description:true,currentPage:true,browserContext:true,status:true,assignedAdminId:true,duplicateOfId:true,internalNote:true,resolutionSummary:true,resolvedAt:true,createdAt:true,submitter:{select:{anonymousDisplayName:true,displayName:true}}}}); return NextResponse.json({ok:true,feedback:items}); } catch(error){return apiErrorResponse(error,'Could not load feedback.',request,'feedback-admin');} }
export async function PATCH(request: NextRequest) { try { const admin=await requireCollegeAdminUser(); const b=await request.json() as {id?:string;status?:string;assignToMe?:boolean;internalNote?:string;duplicateOfId?:string;resolutionSummary?:string}; const current=await prisma.feedback.findUniqueOrThrow({where:{id:b.id}}); const next=b.status&&feedbackStatuses.includes(b.status as never)?b.status as typeof current.status:current.status; if(next!==current.status&&!canTransitionFeedback(current.status,next)) throw new ApiError(409,'Choose a valid feedback status transition.','invalid_feedback_transition'); const resolved=['RESOLVED','DECLINED'].includes(next); const updated=await prisma.$transaction(async tx=>{const item=await tx.feedback.update({where:{id:current.id},data:{status:next,assignedAdminId:b.assignToMe?admin.id:undefined,internalNote:normalizeText(b.internalNote).slice(0,2000)||undefined,duplicateOfId:b.duplicateOfId||undefined,resolutionSummary:normalizeText(b.resolutionSummary).slice(0,1000)||undefined,resolvedAt:resolved?new Date():null}}); if(next!==current.status) await tx.feedbackStatusHistory.create({data:{feedbackId:item.id,status:next,actorId:admin.id}}); await tx.moderationAction.create({data:{moderatorId:admin.id,actionType:`feedback:${next.toLowerCase()}`,targetType:'FEEDBACK',targetId:item.id}}); return item;}); return NextResponse.json({ok:true,status:updated.status}); } catch(error){return apiErrorResponse(error,'Could not update feedback.',request,'feedback-admin');} }
